### ISSUE TITLE
Empty tuple during terraform destroy

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-cloud-dns#8]
Running into the following error when running `terraform destroy`:

```  
on .terraform/modules/xpn-dev.env-dns-private-zone/outputs.tf line 25, in output "name":
  25:   value = element(
  26:
  27:
  28:
  29:
  30:
  31:
  32:
  33:
    |----------------
    | google_dns_managed_zone.forwarding is empty tuple
    | google_dns_managed_zone.peering is empty tuple
    | google_dns_managed_zone.private is empty tuple
    | google_dns_managed_zone.public is empty tuple
```

**Comment by sognern** [comment]
Im having the same issue suddenly, on both create and destroy.

**Comment by wilsonfv** [comment]
this problem is caused by the module [outputs.tf](https://github.com/terraform-google-modules/terraform-google-cloud-dns/blob/master/outputs.tf#L27-L30)

if the actual infrastructure resource has been removed on gcp, when terraform refresh its state file to catch up with latest resource state on gcp, it will return empty tuple since the actual resource has been removed 

i have a workaround locally to bypass the problem 
i will see if i can raise a PR but i need to fix the integration test first
